//! `g8 status` — show and regenerate `.g8/INTENT_SUMMARY.md`.
//!
//! Regenerates the file on each call (unless `--no-regen`), then prints
//! the content to stdout. Per ARCH §10.4, the file has a fixed template.

use std::path::Path;

use anyhow::{Context, Result};
use chrono::Utc;

use g8_conflict::ConflictAdapter;
use g8_conflict::ConflictDetector;
use g8_core::PlanStatus;
use g8_store::{PlanFilter, RusqliteStore, StoreConnection};

use crate::cli::{OutputMode, StatusArgs};
use crate::ctx::{require_init, require_space, Ctx};
use crate::render::json;

pub fn run(ctx: &Ctx, args: &StatusArgs) -> Result<i32> {
    require_init(ctx)?;

    let store = ctx.open_store()?;
    let root = ctx.g8_dir.parent().unwrap_or(&ctx.g8_dir);

    if !args.no_regen {
        regenerate_intent_summary(ctx, &store, root)
            .unwrap_or_else(|e| eprintln!("warn: could not regenerate INTENT_SUMMARY.md: {e:#}"));
    }

    // Read and print the summary.
    let summary_path = ctx.g8_dir.join("INTENT_SUMMARY.md");
    let content = if summary_path.exists() {
        std::fs::read_to_string(&summary_path).context("reading INTENT_SUMMARY.md")?
    } else {
        "(no INTENT_SUMMARY.md found: run `g8 scan` first)".to_string()
    };

    match ctx.output {
        OutputMode::Json => {
            json::render_value(&serde_json::json!({ "intent_summary": content }));
        }
        OutputMode::Pretty => {
            print!("{content}");
        }
    }

    // Intra-space conflicts (optional).
    if args.intra_conflicts {
        let space = require_space(&store, ctx.space_id())?;
        let adapter = ConflictAdapter::new(&store);
        match ConflictDetector::detect_intra_space(&adapter, &space.id) {
            Ok(conflicts) => match ctx.output {
                OutputMode::Json => crate::render::json::render_conflicts(&conflicts),
                OutputMode::Pretty => {
                    crate::render::pretty::render_conflicts(&conflicts, ctx.color)
                }
            },
            Err(e) => eprintln!("warn: intra-conflict detection failed: {e:#}"),
        }
    }

    Ok(0)
}

/// Regenerate `.g8/INTENT_SUMMARY.md` using the ARCH §10.4 template.
///
/// Called by `g8 scan` after successful writes and by `g8 status`.
pub fn regenerate_intent_summary(ctx: &Ctx, store: &RusqliteStore, root: &Path) -> Result<()> {
    let _ = root; // root used only for future per-path queries

    let space = match store.get_default_space().context("get_default_space")? {
        Some(s) => s,
        None => return Ok(()), // no space yet — skip
    };

    let now_ts = Utc::now().to_rfc3339();

    // In-flight plans.
    let in_flight = store
        .list_plans(
            &space.id,
            PlanFilter {
                status: Some(vec![
                    PlanStatus::Dispatched,
                    PlanStatus::Scoped,
                    PlanStatus::Blocked,
                ]),
                ..Default::default()
            },
        )
        .unwrap_or_default();

    // Parked plans (top 5).
    let parked = store
        .list_plans(
            &space.id,
            PlanFilter {
                status: Some(vec![PlanStatus::Parked]),
                limit: Some(5),
                ..Default::default()
            },
        )
        .unwrap_or_default();

    // Stale plans.
    let stale = store.stale_dispatched_plans(&space.id).unwrap_or_default();

    // WIP budgets — collect substrate names from in-flight plans.
    let substrates: Vec<String> = {
        let mut s: Vec<String> = in_flight
            .iter()
            .filter_map(|p| p.substrate.clone())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();
        s.sort();
        s
    };

    // Decisions (recent 5 accepted).
    let decisions = store.list_decisions(&space.id).unwrap_or_default();
    let accepted_decisions: Vec<_> = decisions
        .iter()
        .filter(|d| d.status == g8_core::model::DecisionStatus::Accepted)
        .take(5)
        .collect();

    // Intents (top architectural).
    let intents = store
        .list_intents_at_path(&space.id, Path::new(""))
        .unwrap_or_default();
    let arch_intents: Vec<_> = intents
        .iter()
        .filter(|i| i.kind == g8_core::IntentKind::ArchitecturalScope)
        .take(5)
        .collect();

    // Members count.
    let projects = store.list_projects(&space.id).unwrap_or_default();

    // Build the Markdown template per ARCH §10.4.
    let mut md = String::new();
    md.push_str(&format!(
        "<!-- AUTO-GENERATED by g8 v0.1.0 at {now_ts} -->\n"
    ));
    md.push_str("<!-- Do not edit by hand. Regenerated on each `g8 scan` and `g8 status`. -->\n\n");
    md.push_str("# G8 Intent Summary\n\n");

    md.push_str("## Space\n");
    md.push_str(&format!("Name: {}\n", space.name));
    md.push_str(&format!("Root: {}\n", space.root_path.display()));
    md.push_str(&format!("Members: {} project(s)\n\n", projects.len()));

    md.push_str("## In-Flight Plans\n");
    if in_flight.is_empty() {
        md.push_str("None\n");
    } else {
        md.push_str("| id | title | status | substrate | wip |\n");
        md.push_str("|---|---|---|---|---|\n");
        for p in &in_flight {
            md.push_str(&format!(
                "| {} | {} | {:?} | {} | {} |\n",
                &p.id.as_str()[..p.id.as_str().len().min(8)],
                p.title,
                p.status,
                p.substrate.as_deref().unwrap_or("-"),
                p.wip_weight
            ));
        }
    }
    md.push('\n');

    md.push_str("## WIP Cap Status\n");
    if substrates.is_empty() {
        md.push_str("No substrates with active plans.\n");
    } else {
        md.push_str("| substrate | active | cap | available |\n");
        md.push_str("|---|---|---|---|\n");
        for sub in &substrates {
            let active = in_flight
                .iter()
                .filter(|p| {
                    p.substrate.as_deref() == Some(sub) && p.status == PlanStatus::Dispatched
                })
                .count();
            let budget = store
                .get_substrate_budget(&space.id, sub)
                .unwrap_or_else(|_| g8_core::SubstrateBudget::default_for(sub.clone()));
            let available = (budget.wip_cap as i64) - (active as i64);
            md.push_str(&format!(
                "| {sub} | {active} | {} | {} |\n",
                budget.wip_cap, available
            ));
        }
    }
    md.push('\n');

    md.push_str("## Parked Ideas (top 5 by recency)\n");
    if parked.is_empty() {
        md.push_str("None\n");
    } else {
        for p in &parked {
            let reason = p
                .parked_reason
                .as_deref()
                .map(|r| format!(": {r}"))
                .unwrap_or_default();
            md.push_str(&format!("- {}{}\n", p.title, reason));
        }
    }
    md.push('\n');

    md.push_str("## Stale Promotion Proposals\n");
    if stale.is_empty() {
        md.push_str("None\n");
    } else {
        for s in &stale {
            md.push_str(&format!(
                "- {} ({}d stale): run `g8 plan park {}` or `g8 plan complete {}`\n",
                s.title,
                s.days_stale,
                s.plan_id.as_str(),
                s.plan_id.as_str()
            ));
        }
    }
    md.push('\n');

    md.push_str("## Top Architectural Intents\n");
    if arch_intents.is_empty() {
        md.push_str("None\n");
    } else {
        for i in &arch_intents {
            let owner = i
                .owner
                .as_ref()
                .and_then(|o| o.agent.as_deref())
                .unwrap_or("-");
            md.push_str(&format!(
                "- {} | {} | {}\n",
                i.heading,
                i.scope_path.display(),
                owner
            ));
        }
    }
    md.push('\n');

    md.push_str("## Boundary Alerts\n");
    md.push_str("(run `g8 status --intra-conflicts` to detect boundary violations)\n\n");

    md.push_str("## Decisions (recent 5 accepted)\n");
    if accepted_decisions.is_empty() {
        md.push_str("None\n");
    } else {
        for d in &accepted_decisions {
            md.push_str(&format!("- {}\n", d.title));
        }
    }
    md.push('\n');

    let summary_path = ctx.g8_dir.join("INTENT_SUMMARY.md");
    std::fs::write(&summary_path, &md)
        .with_context(|| format!("writing {}", summary_path.display()))?;

    Ok(())
}
